[tool.black]
line-length = 120
target-version = ['py38',]
experimental_string_processing = true

[tool.isort]
profile = 'black'
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
markers = [
	"slow",
]
addopts = "--durations=0 --strict-markers --doctest-modules"
filterwarnings = [
	"ignore::DeprecationWarning",
	"ignore::UserWarning",
]
testpaths = [
	"tests",
]
